services:
  frontend:
    image: kaipie/easy-teach-frontend:latest
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    command: sleep infinity
    working_dir: /app
    environment:
      - NODE_ENV=development

  backend:
    image: kaipie/easy-teach-backend:latest
    working_dir: /app
    command: sleep infinity
    volumes:
      - .:/app
      - pip_cache:/root/.cache/pip
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1

volumes:
  pip_cache:
