"""Record whether a courseware plan was generated by AI or a template."""

from alembic import op
import sqlalchemy as sa


revision = "0008_courseware_ai_metadata"
down_revision = "0007_task_queue_quality"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.add_column(
        "courseware_plans",
        sa.Column("generation_mode", sa.String(length=16), nullable=False, server_default="template"),
    )
    op.add_column("courseware_plans", sa.Column("model_name", sa.String(length=128)))
    op.add_column("courseware_plans", sa.Column("prompt_version", sa.String(length=64)))
    op.add_column(
        "courseware_plans",
        sa.Column("usage_json", sa.JSON(), nullable=False, server_default="{}"),
    )
    op.create_index(
        "ix_courseware_plans_generation_mode",
        "courseware_plans",
        ["generation_mode"],
    )


def downgrade() -> None:
    op.drop_index("ix_courseware_plans_generation_mode", table_name="courseware_plans")
    op.drop_column("courseware_plans", "usage_json")
    op.drop_column("courseware_plans", "prompt_version")
    op.drop_column("courseware_plans", "model_name")
    op.drop_column("courseware_plans", "generation_mode")
